create DATABASE WEATHER;

CREATE TABLE 
    WEATHER(TEMPRATURE VARCHAR,
        HUMIDITY VARCHAR,
        WIND VARCHAR,
        LOCATION VARCHAR,
        DATE VARCHAR,CONDITION VARCHAR)

create TABLE 
    TRANSPORT(TRANSPORTNUMBER VARCHAR,
        LOCATION VARCHAR
        )
